birdathon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('birds/', views.birds_index, name='index'),
    path('birds/<int:bird_id>/', views.birds_detail, name='detail'),
    path('birds/create/', views.BirdCreate.as_view(), name='birds_create'),
    path('birds/<int:pk>/update/', views.BirdUpdate.as_view(), name='birds_update'),
    path('birds/<int:pk>/delete/', views.BirdDelete.as_view(), name='birds_delete'),
    path('birds/<int:bird_id>/add_sighting/', views.add_sighting, name='add_sighting'),

]

main_app/models.py
from django.db import models
from django.urls import reverse

SPOTTED = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('N', 'Night')
)





# Create your models here.
class Bird(models.Model):
        name = models.CharField(max_length=100)
        family = models.CharField(max_length=100)
        habitat = models.CharField(max_length=100)
        food = models.CharField(max_length=100)
        nesting = models.CharField(max_length=100)
        behavior = models.CharField(max_length=100)
        description = models.TextField(max_length=250)

       
        def __str__(self):
            return self.name
        
        def get_absolute_url(self):
            return reverse('detail', kwargs={'bird_id': self.id})

class Sighting(models.Model):
    date = models.DateField('Sighting Date')
    time = models.CharField(
        max_length=1,
        choices=SPOTTED,
        default=SPOTTED[0][0]
        )

    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_time_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Sighting

class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = ['date', 'time']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Bird
from .forms import SightingForm
# Create your views here.


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def birds_index(request):
    birds = Bird.objects.all()
    return render(request, 'birds/index.html', { 'birds' : birds })

def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    sighting_form = SightingForm()
    return render(request, 'birds/detail.html', { 'bird' : bird, 'sighting_form': sighting_form })

def add_sighting(request, bird_id):
    form = SightingForm(request.POST)
    if form.is_valid():
        new_sighting = form.save(commit=False)
        new_sighting.bird_id = bird_id
        new_sighting.save()
    return redirect('detail', bird_id=bird_id)


class BirdCreate(CreateView):
    model = Bird
    fields = '__all__'

class BirdUpdate(UpdateView):
    model = Bird
    fields = ('family', 'habitat', 'food', 'nesting', 'behavior', 'description')

class BirdDelete(DeleteView):
    model = Bird
    success_url = '/birds/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Birdathon</h1>
<hr />
<br>
<p>This years Birdathon event takes place on the South Shore of Superior.
    Each person will wander out and take photos of the birds that you see.
    If the birds match any of those on the index page, each person may
    select the date and time of each bird they find. Unsure if you have
    seen the right bird? Click on each bird to read more information
    about it. Please be honest!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Birdathon</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,200&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  </head>
  <body>
    <header class="navbar-fixed" >
      <nav>
        <div class="nav-wrapper"  >
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;Birdathon</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'index' %}">View All The Birds</a></li>
            <li><a href="{% url 'birds_create' %}">Add a Bird</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right" style="padding:15px ;">
        All Rights Reserved, © 2022 Birdathon 
      </div>
    </footer>
  </body>
</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Bird Details</h1>

<div class="row">
<div class="col s6">
  <div class="card">
    <div class="card-content">
    <span class="card-title">{{ bird.name }}</span>
    <p>Family: {{ bird.family }}</p>
    <p>Habitat: {{ bird.habitat }}</p>
    <p>Food: {{ bird.food }}</p>
    <p>Nesting: {{ bird.nesting }}</p>
    <p>Behavior: {{ bird.behavior }}</p>
    <p>Description: {{ bird.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'birds_update' bird.id %}">Edit</a>
    <a href="{% url 'birds_delete' bird.id %}">Delete</a>
  </div>
</div>
</div>
<div class="col s6">
  <form action="{% url 'add_sighting' bird.id %}" method="post">
    {% csrf_token %} {{ sighting_form.as_p }}
    <input type="submit" class="btn" value="Add Sighting" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      {% for sighting in bird.sighting_set.all %}
      <tr>
        <td>{{sighting.date}}</td>
        <td>{{sighting.get_time_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_time');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %} {% block content %}

<h1>The Birds!</h1>

{% for bird in birds %}
<div class="card">
    <a href="{% url 'detail' bird.id %}">
  <div class="card-content">
    <span class="card-title">{{ bird.name }}</span>
    <p>Family: {{ bird.family }}</p>
    <p>Habitat: {{ bird.habitat }}</p>
    <p>Food: {{ bird.food }}</p>
    <p>Nesting: {{ bird.nesting }}</p>
    <p>Behavior: {{ bird.behavior }}</p>
    <p>Description: {{ bird.description }}</p>

  </div>
</a>
</div>

{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} 
{% block content %}
    <h1 class="center-align">Birdathon 2022</h1>
    <img class="responsive-img" src="https://nas-national-prod.s3.amazonaws.com/styles/article_hero_inline/s3/apa_2016_osprey_robert_kimbrell_kk.jpg?itok=fJkMVIQE" />
{% endblock %}  

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Bird</h1>

<h4>
    Are you sure you want to delete
    <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes- Delete!" class="btn red" />
    <a href="{% url 'detail' bird.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1>Edit <span class="black-text">{{object.name}}</span></h1>
{% else %}
<h1>Add a Bird!</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table id="addFormTable">
        {{ form.as_table }}
    </table>
    <input style="margin: 10px;" class="btn teal darken-3" type="submit" value="Add Bird" />
</form>
{% endblock %}